name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install backend dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install coverage pytest

      - name: Run backend tests
        working-directory: ./backend
        run: |
          coverage run -m pytest
          coverage xml  # genera coverage.xml

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ 552a833b-e01c-4223-b06b-13e59695fb61 }}  # solo si es repositorio privado
          files: backend/coverage.xml,frontend/coverage/lcov.info
          flags: backend,frontend
          fail_ci_if_error: true

